#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myspacevim#before"
    autocomplete_method = 'coc'
    enable_guicolors = true
    snippet_engine = 'ultisnips'

[[layers]]
name = 'lsp'

[[layers]]
name = 'fzf'

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
enable = false
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'format'

[[layers]]
name = 'lang#markdown'

[[custom_plugins]]
repo = 'numirias/semshi'
merged = false
